<?php

namespace Database\Seeders;

use App\Models\Realty;
use Illuminate\Database\Seeder;

class RealtySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);

        Realty::create([
            "name"=> "Casa na praia",
            "description"=> "Linda casa a beira mar",
            "price" => "10000000",
            "area" => "500",
            "bathrooms"=> "3",
            "garage"=> "2",
            "address_id"=> 1,
            "user_id"=>1,
            "franchise_id" => 1,
            "status"=> "active",
            "marital status" => "Casado",
            "children" =>"02",
            "pets"=> "Sim",
            "suite" => "01",
            "decision maker" => "Família",
            "location" => "Centros Urbanos",
            "sale_deadline" => "Urgente",
            "financing" => "já financiado",
            "construction" => "Novo",
            "property_type" => "Casa",
            "swap_type" => "Não",
            "sale_type" => "Venda",
            "furniture" => "Sim",
            "parking"=>  "Sim",
            "fumante" => "Sim",
            "work_out" => "Ambos",
            "job_type" => "Comercial",
            "proximity_beach" => "Orla com vista",
        ]);
    }
}
